services:
  server:
    build:
      context: /workspaces/${WORKSPACE}/server
    volumes:
      - "${SERVER_MOUNT}/${PROJECT}/bar/:/app/media/${PROJECT}/bar"
      - "${SERVER_MOUNT}/${PROJECT}/archive/:/app/media/${PROJECT}/archive"
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:8080"
    networks:
      - my_network
    command: ["python", "pydash.py", "--host", "${SERVER_HOST}", "--port", "${SERVER_PORT}", "--datadir", "./media"]

  client:
    build: 
      context: /workspaces/${WORKSPACE}/client
    volumes:
      - "${CLIENT_MOUNT}/${PROJECT}/download/:/app/downloads"
    env_file:
      - .env
    depends_on:
      - server
    networks:
      - my_network
    command: ["python", "scheduled_request.py", "--interval", "${INTERVAL}", "--api", "${API_URL}", "--project", "${PROJECT}", "--ext", "${EXT}"]

networks:
  my_network:
    driver: bridge

volumes:
  server_mount:
  client_mount:
