services:
  redis-compression:
    image: redis:latest
    container_name: redis-compression
    networks:
      - my_network
    ports:
      - "6379:6379"
  compression:
    build:
      context: /workspaces/${WORKSPACE}/compression
    volumes:
      - "${COMPRESSION_MOUNT}/input/:/app/data/input"
      - "${SERVER_MOUNT}/${PROJECT}/bar/:/app/data/compressed"
    env_file:
      - .env
    depends_on:
      - redis-compression
    networks:
      - my_network
    entrypoint: ["/app/compress.sh"]
    
  server:
    build:
      context: /workspaces/${WORKSPACE}/server
    volumes:
      - "${SERVER_MOUNT}/${PROJECT}/bar/:/app/media/${PROJECT}/bar"
      - "${SERVER_MOUNT}/${PROJECT}/archive/:/app/media/${PROJECT}/archive"
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:8080"
    networks:
      - my_network
    command: ["python", "pydash.py", "--host", "${SERVER_HOST}", "--port", "${SERVER_PORT}", "--datadir", "./media"]

  redis-decompression:
    image: redis:latest
    container_name: redis-decompression
    networks:
      - my_network
    ports:
      - "6380:6379"
  broker:
    build:
      context: /workspaces/${WORKSPACE}/broker
    volumes:
      - "${BROKER_MOUNT}/${PROJECT}/download/:/app/downloads"
    env_file:
      - .env
    depends_on:
      - server
      - redis-decompression
    networks:
      - my_network
    command: ["python", "scheduled_request.py", "--interval", "${INTERVAL}", "--api", "${API_URL}", "--project", "${PROJECT}", "--ext", "${EXT}"]

  decompression:
    build:
      context: /workspaces/fastapi-file-streaming/decompression
    volumes:
      - "${BROKER_MOUNT}/${PROJECT}/download/:/app/data/compressed"
      - "${DECOMPRESSION_MOUNT}/output/:/app/data/decompressed"
    env_file:
      - .env
    depends_on:
      - broker
      - redis-decompression
    networks:
      - my_network
    entrypoint: ["/app/decompress.sh"]

networks:
  my_network:
    driver: bridge

volumes:
  server_mount:
  broker_mount:
